services:
  - type: web
    name: portfolio-laravel
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "apache2-foreground" 
